apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  selector:
    matchLabels:
    app: intapi-app
  replicas: 1
  template:
    metadata:
      labels:
        app: intapi-app
    spec:
      containers:
      - name: intapi
        image: yossibnv1506/repos:intapi_{{version}}
        ports:
        - containerPort: 3000
         port: 3000
